// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cf447d32-2d5a-48a4-8457-2e35e724bed6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_oNG1T2uXF",
    "aws_user_pools_web_client_id": "70rdj3o7135a0had4f497jfhhd",
    "oauth": {
        "domain": "igor.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://master.d21ecv5wuv7loy.amplifyapp.com/",
        "redirectSignOut": "https://master.d21ecv5wuv7loy.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://a5v7yhaoxrft5pk45766xvjx5e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsconfig;
